test

diff --git a/.github/workflows/update-1.2.1.yaml b/.github/workflows/update-1.2.1.yaml
--- a/.github/workflows/update-1.2.1.yaml
+++ b/.github/workflows/update-1.2.1.yaml
@@ -45,26 +45,34 @@ jobs:
         run: |
           response=$(ldcli flags update --project ${{ env.DEMO_NAMESPACE }}-ld-demo --flag cartSuggestedItems --semantic-patch -d "$(cat ./.github/workflows/v.1.2.1/cartSuggestedItems.json)")
           echo "$response"
+          count=0
           until [[ $response == *"Successfully updated"* ]] || [[ $response == *"You've exceeded the API rate limit. Try again later. (code: rate_limited)"* ]]; do
-            if [[ $response == *"Successfully updated"* ]]; then
+            if [[ $response == *"Successfully updated"* ]] || [[ $response == *'unknown error occured'*]] || [[ $count -eq 3 ]]; then
               break
             fi
-            echo "You've exceeded the API rate limit, waiting 5 seconds..."
+            echo "Attempt $((count+1)) failed, you've exceeded the API rate limit, waiting 5 seconds..."
             sleep 5
+            ((count++))
             response=$(ldcli flags update --project ${{ env.DEMO_NAMESPACE }}-ld-demo --flag cartSuggestedItems --semantic-patch -d "$(cat ./.github/workflows/v.1.2.1/cartSuggestedItems.json)")
           done
+          if [[ $count -eq 3 ]]; then
+            echo "Error: Failed to update after 3 attempts."
+            exit 1
+          fi
           echo "$response"
 
       - name: Delete Stocks API 
         run: |
           response=$(ldcli flags delete --project ${{ env.DEMO_NAMESPACE }}-ld-demo --flag stocksAPI)
           echo "$response"
+          count=0
           until [[ $response == *"Successfully updated"* ]] || [[ $response == *"You've exceeded the API rate limit. Try again later. (code: rate_limited)"* ]]; do
-            if [[ $response == *"Successfully updated"* ]]; then
+            if [[ $response == *"Successfully updated"* ]] || [[ $response == *'unknown error occured'*]] || [[ $count -eq 3 ]]; then
               break
             fi
-            echo "You've exceeded the API rate limit, waiting 5 seconds..."
+            echo "Attempt $((count+1)) failed, you've exceeded the API rate limit, waiting 5 seconds..."
             sleep 5
+            ((count++))
             response=$(ldcli flags delete --project ${{ env.DEMO_NAMESPACE }}-ld-demo --flag stocksAPI)
           done
           echo "$response"
@@ -74,12 +82,14 @@ jobs:
         run: |
           response=$(ldcli flags update --project ${{ env.DEMO_NAMESPACE }}-ld-demo --flag release-new-investment-stock-api  -d "$(cat ./.github/workflows/v.1.2.1/release-new-investment-stock-api.json)")
           echo "$response"
+          count=0
           until [[ $response == *"Successfully updated"* ]] || [[ $response == *"You've exceeded the API rate limit. Try again later. (code: rate_limited)"* ]]; do
-            if [[ $response == *"Successfully updated"* ]]; then
+            if [[ $response == *"Successfully updated"* ]] || [[ $response == *'unknown error occured'*]] || [[ $count -eq 3 ]]; then
               break
             fi
-            echo "You've exceeded the API rate limit, waiting 5 seconds..."
+            echo "Attempt $((count+1)) failed, you've exceeded the API rate limit, waiting 5 seconds..."
             sleep 5
+            ((count++))
             response=$(ldcli flags update --project ${{ env.DEMO_NAMESPACE }}-ld-demo --flag release-new-investment-stock-api  -d "$(cat ./.github/workflows/v.1.2.1/release-new-investment-stock-api.json)")
           done
           echo "$response"
@@ -88,12 +98,14 @@ jobs:
         run: |
           response=$(ldcli flags update --project ${{ env.DEMO_NAMESPACE }}-ld-demo --flag investment-recent-trade-db -d '{"patch":[{"op":"replace","path":"/name","value":"06 - Release New Recent Trades DB"}]}')
           echo "$response"
+          count=0
           until [[ $response == *"Successfully updated"* ]] || [[ $response == *"You've exceeded the API rate limit. Try again later. (code: rate_limited)"* ]]; do
-            if [[ $response == *"Successfully updated"* ]]; then
+            if [[ $response == *"Successfully updated"* ]] || [[ $response == *'unknown error occured'*]] || [[ $count -eq 3 ]]; then
               break
             fi
-            echo "You've exceeded the API rate limit, waiting 5 seconds..."
+            echo "Attempt $((count+1)) failed, you've exceeded the API rate limit, waiting 5 seconds..."
             sleep 5
+            ((count++))
             response=$(ldcli flags update --project ${{ env.DEMO_NAMESPACE }}-ld-demo --flag investment-recent-trade-db -d '{"patch":[{"op":"replace","path":"/name","value":"06 - Release New Recent Trades DB"}]}')
           done
           echo "$response"
@@ -102,12 +114,14 @@ jobs:
         run: |
           response=$(ldcli flags update --project ${{ env.DEMO_NAMESPACE }}-ld-demo --flag launchClubLoyalty -d '{"patch":[{"op":"replace","path":"/name","value":"07 - Enable Launch Club Loyalty Program"}]}')
           echo "$response"
+          count=0
           until [[ $response == *"Successfully updated"* ]] || [[ $response == *"You've exceeded the API rate limit. Try again later. (code: rate_limited)"* ]]; do
-            if [[ $response == *"Successfully updated"* ]]; then
+            if [[ $response == *"Successfully updated"* ]] || [[ $response == *'unknown error occured'*]] || [[ $count -eq 3 ]]; then
               break
             fi
-            echo "You've exceeded the API rate limit, waiting 5 seconds..."
+            echo "Attempt $((count+1)) failed, you've exceeded the API rate limit, waiting 5 seconds..."
             sleep 5
+            ((count++))
             response=$(ldcli flags update --project ${{ env.DEMO_NAMESPACE }}-ld-demo --flag launchClubLoyalty -d '{"patch":[{"op":"replace","path":"/name","value":"07 - Enable Launch Club Loyalty Program"}]}')
           done
           echo "$response"
@@ -116,12 +130,14 @@ jobs:
         run: |
           response=$(ldcli flags update --project ${{ env.DEMO_NAMESPACE }}-ld-demo --flag priorityBoarding -d '{"patch":[{"op":"replace","path":"/name","value":"08 - Launch Club - Priority Boarding"}]}')
           echo "$response"
+          count=0
           until [[ $response == *"Successfully updated"* ]] || [[ $response == *"You've exceeded the API rate limit. Try again later. (code: rate_limited)"* ]]; do
-            if [[ $response == *"Successfully updated"* ]]; then
+            if [[ $response == *"Successfully updated"* ]] || [[ $response == *'unknown error occured'*]] || [[ $count -eq 3 ]]; then
               break
             fi
-            echo "You've exceeded the API rate limit, waiting 5 seconds..."
+            echo "Attempt $((count+1)) failed, you've exceeded the API rate limit, waiting 5 seconds..."
             sleep 5
+            ((count++))
             response=$(ldcli flags update --project ${{ env.DEMO_NAMESPACE }}-ld-demo --flag priorityBoarding -d '{"patch":[{"op":"replace","path":"/name","value":"08 - Launch Club - Priority Boarding"}]}')
           done
           echo "$response"
@@ -130,12 +146,14 @@ jobs:
         run: |
           response=$(ldcli flags update --project ${{ env.DEMO_NAMESPACE }}-ld-demo --flag mealPromoExperience -d '{"patch":[{"op":"replace","path":"/name","value":"09 - Targeted Plane Meal Promotion"}]}')
           echo "$response"
+          count=0
           until [[ $response == *"Successfully updated"* ]] || [[ $response == *"You've exceeded the API rate limit. Try again later. (code: rate_limited)"* ]]; do
-            if [[ $response == *"Successfully updated"* ]]; then
+            if [[ $response == *"Successfully updated"* ]] || [[ $response == *'unknown error occured'*]] || [[ $count -eq 3 ]]; then
               break
             fi
-            echo "You've exceeded the API rate limit, waiting 5 seconds..."
+            echo "Attempt $((count+1)) failed, you've exceeded the API rate limit, waiting 5 seconds..."
             sleep 5
+            ((count++))
             response=$(ldcli flags update --project ${{ env.DEMO_NAMESPACE }}-ld-demo --flag mealPromoExperience -d '{"patch":[{"op":"replace","path":"/name","value":"09 - Targeted Plane Meal Promotion"}]}')
           done
           echo "$response"
@@ -144,12 +162,14 @@ jobs:
         run: |
           response=$(ldcli flags update --project ${{ env.DEMO_NAMESPACE }}-ld-demo --flag aiTravelInsights -d '{"patch":[{"op":"replace","path":"/name","value":"10 - Release AI Travel Insights"}]}')
           echo "$response"
+          count=0
           until [[ $response == *"Successfully updated"* ]] || [[ $response == *"You've exceeded the API rate limit. Try again later. (code: rate_limited)"* ]]; do
-            if [[ $response == *"Successfully updated"* ]]; then
+            if [[ $response == *"Successfully updated"* ]] || [[ $response == *'unknown error occured'*]] || [[ $count -eq 3 ]]; then
               break
             fi
-            echo "You've exceeded the API rate limit, waiting 5 seconds..."
+            echo "Attempt $((count+1)) failed, you've exceeded the API rate limit, waiting 5 seconds..."
             sleep 5
+            ((count++))
             response=$(ldcli flags update --project ${{ env.DEMO_NAMESPACE }}-ld-demo --flag aiTravelInsights -d '{"patch":[{"op":"replace","path":"/name","value":"10 - Release AI Travel Insights"}]}')
           done
           echo "$response"
@@ -158,12 +178,14 @@ jobs:
         run: |
           response=$(ldcli flags update --project ${{ env.DEMO_NAMESPACE }}-ld-demo --flag featureStoreHeaders -d '{"patch":[{"op":"replace","path":"/name","value":"11 - Featured Store Headers"}]}')
           echo "$response"
+          count=0
           until [[ $response == *"Successfully updated"* ]] || [[ $response == *"You've exceeded the API rate limit. Try again later. (code: rate_limited)"* ]]; do
-            if [[ $response == *"Successfully updated"* ]]; then
+            if [[ $response == *"Successfully updated"* ]] || [[ $response == *'unknown error occured'*]] || [[ $count -eq 3 ]]; then
               break
             fi
-            echo "You've exceeded the API rate limit, waiting 5 seconds..."
+            echo "Attempt $((count+1)) failed, you've exceeded the API rate limit, waiting 5 seconds..."
             sleep 5
+            ((count++))
             response=$(ldcli flags update --project ${{ env.DEMO_NAMESPACE }}-ld-demo --flag featureStoreHeaders -d '{"patch":[{"op":"replace","path":"/name","value":"11 - Featured Store Headers"}]}')
           done
           echo "$response"
@@ -172,12 +194,14 @@ jobs:
         run: |
           response=$(ldcli flags update --project ${{ env.DEMO_NAMESPACE }}-ld-demo --flag storeAttentionCallout -d '{"patch":[{"op":"replace","path":"/name","value":"12 - Store Highlight Text"}]}')
           echo "$response"
+          count=0
           until [[ $response == *"Successfully updated"* ]] || [[ $response == *"You've exceeded the API rate limit. Try again later. (code: rate_limited)"* ]]; do
-            if [[ $response == *"Successfully updated"* ]]; then
+            if [[ $response == *"Successfully updated"* ]] || [[ $response == *'unknown error occured'*]] || [[ $count -eq 3 ]]; then
               break
             fi
-            echo "You've exceeded the API rate limit, waiting 5 seconds..."
+            echo "Attempt $((count+1)) failed, you've exceeded the API rate limit, waiting 5 seconds..."
             sleep 5
+            ((count++))
             response=$(ldcli flags update --project ${{ env.DEMO_NAMESPACE }}-ld-demo --flag storeAttentionCallout -d '{"patch":[{"op":"replace","path":"/name","value":"12 - Store Highlight Text"}]}')
           done
           echo "$response"
@@ -185,14 +209,15 @@ jobs:
       - name: Cart Suggested Items
         run: |
           echo "Updating Cart Suggested Items Feature Flag"
-          response=$(ldcli flags update --project ${{ env.DEMO_NAMESPACE }}-ld-demo --flag cartSuggestedItems -d '{"patch":[{"op":"replace","path":"/name","value":"13 - Cart Suggested items"}]}')
           echo "$response"
+          count=0
           until [[ $response == *"Successfully updated"* ]] || [[ $response == *"You've exceeded the API rate limit. Try again later. (code: rate_limited)"* ]]; do
-            if [[ $response == *"Successfully updated"* ]]; then
+            if [[ $response == *"Successfully updated"* ]] || [[ $response == *'unknown error occured'*]] || [[ $count -eq 3 ]]; then
               break
             fi
-            echo "You've exceeded the API rate limit, waiting 5 seconds..."
+            echo "Attempt $((count+1)) failed, you've exceeded the API rate limit, waiting 5 seconds..."
             sleep 5
+            ((count++))
             response=$(ldcli flags update --project ${{ env.DEMO_NAMESPACE }}-ld-demo --flag cartSuggestedItems -d '{"patch":[{"op":"replace","path":"/name","value":"13 - Cart Suggested items"}]}')
           done
           echo "$response"
